Installs brahms-gdb and brahms-vg, both of which also now check for required dev tools (valgrind or gdb)

diff --git a/framework/execute/brahms-gdb b/framework/execute/brahms-gdb
--- a/framework/execute/brahms-gdb
+++ b/framework/execute/brahms-gdb
@@ -67,9 +67,17 @@
 #export PATH=$PATH:$BINPATH
 #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BINPATH
 
+# Check we have gdb
+GDB=`which gdb`
+rtn=$?
+if [ "$rtn" = "1" ]; then
+    echo "$0: Error: gdb not found"
+    exit 1
+fi
+
 # call BRAHMS executable with UP TO 8 args ONLY!
-echo gdb brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
-gdb --command="~/gdbcmd" --args brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
+echo $GDB brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
+$GDB --command="~/gdbcmd" --args brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
 
 
 # I think this will just pass on the return code to the
@@ -84,6 +92,3 @@ gdb --command="~/gdbcmd" --args brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7
 # then
 # 	exit $ERR
 # fi
-
-
-
diff --git a/framework/execute/brahms-vg b/framework/execute/brahms-vg
--- a/framework/execute/brahms-vg
+++ b/framework/execute/brahms-vg
@@ -67,9 +67,17 @@ BINPATH=`echo $0 | sed s/\\\\\(.*\\\\\)\\\/.*/\\\1/`
 export PATH=$PATH:$BINPATH
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BINPATH
 
+# Check we have valgrind
+VALGRIND=`which valgrind`
+rtn=$?
+if [ "$rtn" = "1" ]; then
+    echo "$0: Error: valgrind not found"
+    exit 1
+fi
+
 # call BRAHMS executable with UP TO 8 args ONLY!
-echo valgrind brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
-valgrind brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
+echo $VALGRIND --leak-check=full brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
+$VALGRIND --leak-check=full brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
 
 
 # I think this will just pass on the return code to the
@@ -84,6 +92,3 @@ valgrind brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
 # then
 # 	exit $ERR
 # fi
-
-
-
